### PR TITLE
Fix the build with swiften 4.0rc5

### LINKED ISSUE #32: Shmoose no longer builds after updating swiften to 4.0rc5
```
g++ -c -pipe -DSWIFT_EXPERIMENTAL_FT -DSWIFT_EXPERIMENTAL_FT -DSWIFT_EXPERIMENTAL_FT -I/usr/bin/../include -I/usr/bin/../include -I/usr/bin/../include -std=c++11 -Wno-deprecated-declarations -Wno-placement-new -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../swift-3.0-host/3rdParty/Boost/src -I../swift-3.0-host/ -Isource -Isource/persistence -Isource/xep/httpFileUpload -Isource/xep/xmppPing -Isource/xep/chatMarkers -isystem /usr/include/qt -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-g++ -o RosterContoller.o source/RosterContoller.cpp
source/RosterContoller.cpp: In member function ‘void RosterController::addContact(const QString&, const QString&)’:
source/RosterContoller.cpp:341:95: error: no matching function for call to ‘Swift::IQ::createRequest(Swift::IQ::Type, Swift::JID, std::__cxx11::string&, boost::shared_ptr<Swift::RosterPayload>&)’
         iqRouter->sendIQ(Swift::IQ::createRequest(Swift::IQ::Set, Swift::JID(), msgId, payload));
                                                                                               ^
In file included from /usr/include/Swiften/Queries/Request.h:16:0,
                 from /usr/include/Swiften/Queries/GenericRequest.h:12,
                 from /usr/include/Swiften/Whiteboard/OutgoingWhiteboardSession.h:18,
                 from /usr/include/Swiften/Swiften.h:5,
                 from source/RosterContoller.h:6,
                 from source/RosterContoller.cpp:1:
/usr/include/Swiften/Elements/IQ.h:27:40: note: candidate: static std::shared_ptr<Swift::IQ> Swift::IQ::createRequest(Swift::IQ::Type, const Swift::JID&, const string&, std::shared_ptr<Swift::Payload>)
             static std::shared_ptr<IQ> createRequest(
                                        ^~~~~~~~~~~~~
/usr/include/Swiften/Elements/IQ.h:27:40: note:   no known conversion for argument 4 from ‘boost::shared_ptr<Swift::RosterPayload>’ to ‘std::shared_ptr<Swift::Payload>’
source/RosterContoller.cpp: In member function ‘void RosterController::removeContact(const QString&)’:
source/RosterContoller.cpp:358:91: error: no matching function for call to ‘Swift::IQ::createRequest(Swift::IQ::Type, Swift::JID, std::__cxx11::string&, boost::shared_ptr<Swift::RosterPayload>&)’
     iqRouter->sendIQ(Swift::IQ::createRequest(Swift::IQ::Set, Swift::JID(), msgId, payload));
                                                                                           ^
In file included from /usr/include/Swiften/Queries/Request.h:16:0,
                 from /usr/include/Swiften/Queries/GenericRequest.h:12,
                 from /usr/include/Swiften/Whiteboard/OutgoingWhiteboardSession.h:18,
                 from /usr/include/Swiften/Swiften.h:5,
                 from source/RosterContoller.h:6,
                 from source/RosterContoller.cpp:1:
/usr/include/Swiften/Elements/IQ.h:27:40: note: candidate: static std::shared_ptr<Swift::IQ> Swift::IQ::createRequest(Swift::IQ::Type, const Swift::JID&, const string&, std::shared_ptr<Swift::Payload>)
             static std::shared_ptr<IQ> createRequest(
                                        ^~~~~~~~~~~~~
/usr/include/Swiften/Elements/IQ.h:27:40: note:   no known conversion for argument 4 from ‘boost::shared_ptr<Swift::RosterPayload>’ to ‘std::shared_ptr<Swift::Payload>’
make: *** [Makefile:819: RosterContoller.o] Error 1
```

it looks like swiften has moved from `boost::shared_ptr` to `std::shared_ptr`

### PR DESCRIPTION
**Pull request by marmistrz**
Fix the build with swiften 4.0rc5. Depends on #28. Closes #32.

### CODE REVIEW

**Comment by geobra** [comment]
This breaks the build in mersdk. Since SFOS is the main target, that must be fixed.

**Comment by marmistrz** [comment]
Which version of swiften are you building against? What is the error?

I don't currently have swiften compiled in MerSDK (I'm trying to get an OBS build which is, well, troublesome)

Btw. we really need some Travis to automatically check, if a PR doesn't break anything.

**Comment by geobra** [comment]
I build against swift version 3.0. This is the latest stable.

Indeed. Travis would make things a lot more easier. Especially now, when more developers work on it. Which I really appreciate!

**Comment by marmistrz** [comment]
Swiften 4.0rc5 is not API-compatible with Swiften 3.0, that's the reason. It uses `std::shared_ptr` everywhere it used `boost::shared_ptr` (at least where I have seen it)
Shall we wait until 4.0 finishes the rc phase?

**Comment by geobra** [comment]
Yes, makes sense. We can switch to 4.0 as soon as it's released.

**Comment by marmistrz** [comment]
I think we should reconsider switching to 4.0 even if it's beta right now. This would fix #34.

**Comment by geobra** [comment]
The Problem ist, you don't know what other bugs you get while switching to a RC.
In my opinion its better to stay at a stable version at mainline. But we can make a branch and test the 4.0RC version there.

**Comment by marmistrz** [comment]
That means, that if we encounter any bugs, we may report them upstream and expect them to be fixed in the final version. Otherwise we may have to wait a very long time until they hit the stable.

I think that's ok, shmoose beta built against a beta version of swiften. I'd even put it into openrepos as shmoose beta so that we get testers.

**Comment by marmistrz** [comment]
That means, that if we encounter any bugs, we may report them upstream and expect them to be fixed in the final version. Otherwise we may have to wait a very long time until they hit the stable.

I think that's ok, shmoose beta built against a beta version of swiften. I'd even put it into openrepos as shmoose beta so that we get testers.

Could you test if there are no problems building shmoose against swiften 4 under MerSDK? I'll be unfortunately quite busy during the next two weeks, so if I have some spare time for shmoose, I'd rather get the QML changes polished. (that's more likely not to take a lot of time)

`std::shared_ptr` are the part of C++11, so you may need rinigus's GCC6: https://talk.maemo.org/showthread.php?t=99699 (starting with post 10)

**Comment by geobra** [comment]
Good point. From that point of view we really should do a beta build. This would also fit perfect to test the omemo implementation. Before I setup this beta environment I want to finish the first omemo beta implementation. I don't want to switch between such big targets. Let's get one thing ready after another.

**Comment by rehejuhan** [comment]
Swift 4.0 is released: https://swift.im/docs/changelog-4-0.html

**Comment by geobra** [comment]
Good news. Let me check how difficult it is to get it compiled for SFOS. As far as I know, some new libs will be needed on the device side...

**Comment by marmistrz** [comment]
You're likely to need newer boost, but I don't remember that.

**Comment by geobra** [comment]
Made a test build. On my Debian host system, all went really well. Boost is not an issue, its included in the swift package and used if the host does not deliver an appropriate version. But the problem within mersdk is the old compiler. Does not work with swift 4.0.2. So instead of trying to update this or use some newer versions from other devs I want to wait for SFOS 3. This should be available this year with an new mersdk. I will have a next try when this is released.

**Comment by GNUuser** [comment]
ok folks @geobra @marmistrz sailfish 3 is out  now :  )

**Comment by rogora** [comment]
FYI, I managed to compile Shmoose with Swiften 4.0. As expected, I had to use rinigus's GCC6, which makes the compilation way slower, for some reason. 

@marmistrz 's patch is  almost correct, but some minor modifications to source/xep/xmppPing/PingRequest.h are needed to make it compile.

Finally, to run Shmoose on my Jolla phone, I also have install rinigus's GCC6 and add LD_LIBRARY_PATH=/opt/gcc6/lib/ to make it load the correct version of libstdc++.so, but then it works without problems, as far as I can see.

**Comment by geobra** [comment]
Did a cherry picking here for the swift 4.0.2 update, as the original pull request has conflicts now.
