### ISSUE TITLE
Shmoose no longer builds after updating swiften to 4.0rc5

### ISSUE THREAD

**Issue by marmistrz** [geobra/harbour-shmoose#32]
```
g++ -c -pipe -DSWIFT_EXPERIMENTAL_FT -DSWIFT_EXPERIMENTAL_FT -DSWIFT_EXPERIMENTAL_FT -I/usr/bin/../include -I/usr/bin/../include -I/usr/bin/../include -std=c++11 -Wno-deprecated-declarations -Wno-placement-new -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../swift-3.0-host/3rdParty/Boost/src -I../swift-3.0-host/ -Isource -Isource/persistence -Isource/xep/httpFileUpload -Isource/xep/xmppPing -Isource/xep/chatMarkers -isystem /usr/include/qt -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-g++ -o RosterContoller.o source/RosterContoller.cpp
source/RosterContoller.cpp: In member function ‘void RosterController::addContact(const QString&, const QString&)’:
source/RosterContoller.cpp:341:95: error: no matching function for call to ‘Swift::IQ::createRequest(Swift::IQ::Type, Swift::JID, std::__cxx11::string&, boost::shared_ptr<Swift::RosterPayload>&)’
         iqRouter->sendIQ(Swift::IQ::createRequest(Swift::IQ::Set, Swift::JID(), msgId, payload));
                                                                                               ^
In file included from /usr/include/Swiften/Queries/Request.h:16:0,
                 from /usr/include/Swiften/Queries/GenericRequest.h:12,
                 from /usr/include/Swiften/Whiteboard/OutgoingWhiteboardSession.h:18,
                 from /usr/include/Swiften/Swiften.h:5,
                 from source/RosterContoller.h:6,
                 from source/RosterContoller.cpp:1:
/usr/include/Swiften/Elements/IQ.h:27:40: note: candidate: static std::shared_ptr<Swift::IQ> Swift::IQ::createRequest(Swift::IQ::Type, const Swift::JID&, const string&, std::shared_ptr<Swift::Payload>)
             static std::shared_ptr<IQ> createRequest(
                                        ^~~~~~~~~~~~~
/usr/include/Swiften/Elements/IQ.h:27:40: note:   no known conversion for argument 4 from ‘boost::shared_ptr<Swift::RosterPayload>’ to ‘std::shared_ptr<Swift::Payload>’
source/RosterContoller.cpp: In member function ‘void RosterController::removeContact(const QString&)’:
source/RosterContoller.cpp:358:91: error: no matching function for call to ‘Swift::IQ::createRequest(Swift::IQ::Type, Swift::JID, std::__cxx11::string&, boost::shared_ptr<Swift::RosterPayload>&)’
     iqRouter->sendIQ(Swift::IQ::createRequest(Swift::IQ::Set, Swift::JID(), msgId, payload));
                                                                                           ^
In file included from /usr/include/Swiften/Queries/Request.h:16:0,
                 from /usr/include/Swiften/Queries/GenericRequest.h:12,
                 from /usr/include/Swiften/Whiteboard/OutgoingWhiteboardSession.h:18,
                 from /usr/include/Swiften/Swiften.h:5,
                 from source/RosterContoller.h:6,
                 from source/RosterContoller.cpp:1:
/usr/include/Swiften/Elements/IQ.h:27:40: note: candidate: static std::shared_ptr<Swift::IQ> Swift::IQ::createRequest(Swift::IQ::Type, const Swift::JID&, const string&, std::shared_ptr<Swift::Payload>)
             static std::shared_ptr<IQ> createRequest(
                                        ^~~~~~~~~~~~~
/usr/include/Swiften/Elements/IQ.h:27:40: note:   no known conversion for argument 4 from ‘boost::shared_ptr<Swift::RosterPayload>’ to ‘std::shared_ptr<Swift::Payload>’
make: *** [Makefile:819: RosterContoller.o] Error 1
```

it looks like swiften has moved from `boost::shared_ptr` to `std::shared_ptr`

**Comment by marmistrz** [comment]
I have the compile fix phased. I need to fix some link errors and I'll file a PR.

**Comment by geobra** [comment]
resolved with EA of SFOS.
